volumes:
  mysql-data:

#networks:
#  app-network:
#    driver: overlay

services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: defaultdb
    ports:
     - "3306:3306"
#    networks:
#      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure